[workspace]

resolver = "2"
members = [
    "lib",
    "app"
]

[profile.release] # https://github.com/johnthagen/min-sized-rust
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true  
