[package]
name = "plc"
version = "0.1.0"
edition = "2021"
authors = [
    "Vyacheslav Zalygin @vzalygin"
]
description = "postfix language compiler"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
anyhow = "1.0"
lib = { path = "../lib" }
