name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  OPTIONS: --manifest-path ./compiler/Cargo.toml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup toolchain
      run: rustup toolchain install stable --profile minimal

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: compiler

    - name: Lint
      run: cargo fmt --check --all $OPTIONS

    - name: Build
      run: cargo build --verbose $OPTIONS

    - name: Clippy
      run: cargo clippy $OPTIONS

    - name: Unit tests
      run: cargo test --verbose $OPTIONS
