name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup toolchain
      run: rustup toolchain install stable --profile minimal

    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: compiler
    
    - name: Setup apt deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: nasm
          version: 1.0

    - name: Lint
      run: cargo fmt --check --all

    - name: Build
      run: cargo build --verbose

    - name: Clippy
      run: cargo clippy

    - name: Unit tests
      run: cargo test --verbose --all-targets --workspace --exclude e2e

    - name: E2E tests
      run: cargo test --verbose --all-targets --package e2e
