name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SPECIFIC_COMPILER_MANIFEST: --manifest-path ./compiler/Cargo.toml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo fmt --check --all $SPECIFIC_COMPILER_MANIFEST
    - name: Codestyle
      run: cargo clippy $SPECIFIC_COMPILER_MANIFEST
    - name: Build
      run: cargo build --verbose $SPECIFIC_COMPILER_MANIFEST
    - name: Run unit tests
      run: cargo test --verbose $SPECIFIC_COMPILER_MANIFEST
